UPDATE EDIREGISTRO ER SET ER.ESTADOINTEGRACAO = 3 WHERE ER.DADO006 = DocSaida AND ER.TIPOINTEGRACAO = 1004;

SELECT ED.SEQUENCIAINTEGRACAO,
       ED.SEQUENCIAINTEGRACAO,
       ED.ESTADOINTEGRACAO,
       ED.DATALOG,
       ED.DATAINTEGRACAO,
       ED.DADO001,
       ED.DADO002,
       ED.DADO003,
       ED.DADO004,
       ED.DADO005,
       ED.DADO006,
       ED.NOMEARQUIVO
FROM EDIREGISTRO ED
WHERE ED.DADO006 = 81465082
AND ED.TIPOINTEGRACAO = 1004

SELECT *
