SELECT CLIENT_NAME, STATUS FROM DBA_AUTOTASK_CLIENT

select * from DBA_OPTSTAT_OPERATIONS

select owner, TABLE_NAME, STATS_UPDATE_TIME from DBA_TAB_STATS_HISTORY WHERE OWNER = 'WMAS'

select OWNER, TABLE_NAME, NUM_ROWS, SAMPLE_SIZE, LAST_ANALYZED from DBA_TAB_PENDING_STATS;