SELECT DS.DOCUMENTOSAIDA,
       DS.QUANTIDADEVOLUME
  FROM DOCUMENTOSAIDA DS
 WHERE DS.CODIGODEPOSITANTE = '53162095002400'
   AND DS.TIPODOCUMENTO = 'NF'
   AND NOT EXISTS (SELECT 1
                     FROM CONFERENCIA CN 
                    WHERE CN.CODIGODOCUMENTO = DS.CODIGODOCUMENTO 
                      AND CN.ESTADOCONFERENCIA = 5)
  
