SELECT RH.CODIGORECURSO,
       RH.USUARIO,
       RH.DATAHISTORICOANTERIOR,
       RH.DATAHISTORICOATUAL,
       SU.COLETORIP
       FROM RECURSOHISTORICO RH,
            SEGUSUARIO SU
       WHERE RH.CODIGORECURSO = SU.CODIGOPESSOA
         --AND RH.CODIGORECURSO = 158
         AND SU.COLETORIP = '10.13.0.42'
