ALTER PROCEDURE [dbo].[SP_BID_STATUS_ROMANEIO_STORE] (@DATA_INI DATETIME,@DATA_FIN DATETIME) AS
-- ROMANEIOS --
  SELECT --E.DESCRICAOEMPRESA,
         --R.TIPOROMANEIO,
         ER.DESCRICAOESTADOROMANEIO,
         COUNT(1) AS TOTAL
    FROM [GATDB01]..[WMAS].[ROMANEIO] R, 
         [GATDB01]..[WMAS].[EMPRESA] E, 
         [GATDB01]..[WMAS].[ESTADOROMANEIO] ER
   WHERE R.CODIGODEPOSITANTE = E.CODIGOEMPRESA
     AND R.ESTADOROMANEIO = ER.ESTADOROMANEIO
     AND E.DEPOSITANTE = 1 
     AND R.CODIGOESTABELECIMENTO = 1
     AND R.ESTADOROMANEIO <> 10
     AND R.TIPOROMANEIO = 'E'
     AND R.DATAEMISSAO >= @DATA_INI --GETDATE()--
	   AND R.DATAEMISSAO <= @DATA_FIN --GETDATE()--
GROUP BY R.TIPOROMANEIO, E.DESCRICAOEMPRESA, ER.DESCRICAOESTADOROMANEIO
ORDER BY E.DESCRICAOEMPRESA, R.TIPOROMANEIO, ER.DESCRICAOESTADOROMANEIO
