SELECT DS.CODIGODEPOSITANTE,
       DS.DATAEMISSAO,
       DS.DATAMOVIMENTO,
       DS.DOCUMENTOSAIDA,
       DS.DOCUMENTOQUALIDADE,
       DS.ESTADODOCUMENTO,       
       DS.QUANTIDADEVOLUME,
       --DS.CODIGODOCUMENTO,
       QTDVOLCONF.QTDVOL
  FROM DOCUMENTOSAIDA DS,
       (SELECT DISTINCT
               CN.CODIGODOCUMENTO,
         COUNT(CN.CODIGOEMBALAGEMEXPED) AS QTDVOL
          FROM CONFERENCIA CN 
         WHERE CN.ESTADOCONFERENCIA = 5
      GROUP BY CN.CODIGODOCUMENTO) QTDVOLCONF
 WHERE DS.CODIGODOCUMENTO = QTDVOLCONF.CODIGODOCUMENTO
   AND DS.CODIGOESTABELECIMENTO = 1
   AND DS.CODIGODEPOSITANTE = '53162095002400'
   AND DS.TIPODOCUMENTO = 'NF'
   AND DS.ESTADODOCUMENTO = 25
   AND DS.QUANTIDADEVOLUME <> QTDVOLCONF.QTDVOL
   --AND DS.DOCUMENTOSAIDA = '409451'
   
-- UPDATE DOS DOCUMENTOS COM TOTAL DE VOLUME DIFERENTE DA CONFERENCIA --
   
UPDATE DOCUMENTOSAIDA DS
   SET DS.QUANTIDADEVOLUME = (SELECT DISTINCT COUNT(CN.CODIGOEMBALAGEMEXPED)
                                FROM CONFERENCIA CN 
                               WHERE CN.CODIGODOCUMENTO = DS.CODIGODOCUMENTO 
                                 AND CN.ESTADOCONFERENCIA = 5)
 WHERE DS.CODIGOESTABELECIMENTO = 1
   AND DS.CODIGODEPOSITANTE = '53162095002400'
   AND DS.TIPODOCUMENTO = 'NF'
   AND DS.ESTADODOCUMENTO = 25
   AND DS.QUANTIDADEVOLUME <> (SELECT DISTINCT COUNT(CN.CODIGOEMBALAGEMEXPED)
                                 FROM CONFERENCIA CN 
                                WHERE CN.CODIGODOCUMENTO = DS.CODIGODOCUMENTO 
                                  AND CN.ESTADOCONFERENCIA = 5)
