UPDATE LOTEENTRADASEQUENCIA SEQ SET SEQ.LOTEGERAL = SUBSTR(SEQ.DATAFABRICACAO,1,10) ||'-'|| SUBSTR(SEQ.DATAVENCIMENTO,1,10), SEQ.CLASSEPRODUTO = 'BLQDS', SEQ.DATAFABRICACAO = '', SEQ.DATAVENCIMENTO = ''
WHERE SEQ.CODIGOESTABELECIMENTO = 1
AND SEQ.LOTEENTRADA = ( SELECT LOT.LOTEENTRADA FROM LOTEENTRADA LOT WHERE LOT.LOTEENTRADA = SEQ.LOTEENTRADA AND LOT.CODIGOMATRIZ = '53162095002400' AND LOT.CODIGOPRODUTO = '1500065' )
AND (SEQ.QUANTIDADEATUAL + SEQ.QUANTIDADEEMPENHADO + SEQ.QUANTIDADEBLOQUEADO) > 0
