SELECT PS.CODIGOESTABELECIMENTO,
       (SELECT EST.NOMEESTABELECIMENTO FROM ESTABELECIMENTO EST WHERE EST.CODIGOESTABELECIMENTO = PS.CODIGOESTABELECIMENTO) AS NOME_ESTABELECIMENTO,
       PS.CODIGOTRANSPORTADORA,       
       (SELECT E.DESCRICAOEMPRESA FROM EMPRESA E WHERE E.CODIGOEMPRESA = PS.CODIGOTRANSPORTADORA) AS TRANSPORTADORA_NF,
       PS.CODIGOEMPRESA,
       (SELECT E.DESCRICAOEMPRESA FROM EMPRESA E WHERE E.CODIGOEMPRESA = PS.CODIGOEMPRESA) AS DESTINATARIO,
       (SELECT E.CEPEMPRESA FROM EMPRESA E WHERE E.CODIGOEMPRESA = PS.CODIGOEMPRESA) AS CEP,
       (SELECT E.UFEMPRESA FROM EMPRESA E WHERE E.CODIGOEMPRESA = PS.CODIGOEMPRESA) AS UF,
       (SELECT REG.IDREGIAO
          FROM REGIAO REG,
               REGIAOSEQUENCIA REGS
         WHERE REG.CODIGOREGIAO = REGS.CODIGOREGIAO
           AND REPLACE(REGS.CEPINICIAL,'-','') <= (SELECT REPLACE(EMP.CEPEMPRESA,'-','')
                                                    FROM EMPRESA EMP
                                                   WHERE EMP.CODIGOEMPRESA = PS.CODIGOEMPRESA)
           AND REPLACE(REGS.CEPFINAL,'-','') >= (SELECT REPLACE(EMP.CEPEMPRESA,'-','')
                                                  FROM EMPRESA EMP
                                                 WHERE EMP.CODIGOEMPRESA = PS.CODIGOEMPRESA)) AS ROTA,
       
       PS.DATAEMISSAO,
       PS.DATAGERACAO,
       LS.NUMEROPEDIDOSEPARACAO NUMEROREMESSA,
       DECODE(PS.TIPODOCUMENTO,
              'PED',NULL,
              PS.PREVISAOSAIDA) NUMERONF,
       COUNT(LS.CODIGOPRODUTO) AS QTD_ITENS_REMESSA,
       SUM(LS.QTDE) AS QTD_UN_ITENS,
       LS.CLASSEPRODUTO,
       SUM(TRUNC(LS.QTDE/UC.MAXFT)) QTDECX,
       DECODE(SUM(MOD(LS.QTDE,UC.MAXFT)),
              0, 0,
              1) QTDE_CX_FRAC,
       PS.ESTADODOCUMENTO,
       (SELECT EDOC.DESCRICAOESTADODOCUMENTO FROM ESTADODOCUMENTO EDOC WHERE EDOC.ESTADODOCUMENTO = PS.ESTADODOCUMENTO) AS STATUS_DOC      
  FROM PREVISAOSAIDA PS,
       (SELECT XLS.CODIGOESTABELECIMENTO,
               XLS.CODIGOMATRIZ,
               XLS.CODIGOEMPRESA,
               XLS.TIPODOCUMENTO,
               XLS.SERIEDOCUMENTO,
               XLS.PREVISAOSAIDA,
               XLS.NUMEROPEDIDOSEPARACAO,
               XLS.CODIGOPRODUTO,
               XLS.CLASSEPRODUTO,
               SUM(XLS.QUANTIDADEDOCUMENTO*XLS.FATORTIPOUC) QTDE
          FROM PREVISAOSAIDAITEM XLS
         GROUP BY XLS.CODIGOESTABELECIMENTO,
               XLS.CODIGOMATRIZ,
               XLS.CODIGOEMPRESA,
               XLS.TIPODOCUMENTO,
               XLS.SERIEDOCUMENTO,
               XLS.PREVISAOSAIDA,
               XLS.NUMEROPEDIDOSEPARACAO,
               XLS.CODIGOPRODUTO,
               XLS.CLASSEPRODUTO) LS,         
       (SELECT T.CODIGOEMPRESA, T.CODIGOPRODUTO,
               MAX(T.FATORTIPOUC) MAXFT
          FROM TIPOUC T
         WHERE T.FATORTIPOUC > 1
         GROUP BY T.CODIGOEMPRESA, T.CODIGOPRODUTO) UC,
       EMPRESA TRA
 WHERE PS.CODIGOESTABELECIMENTO=LS.CODIGOESTABELECIMENTO
   AND PS.CODIGOEMPRESA=LS.CODIGOEMPRESA
   AND PS.TIPODOCUMENTO=LS.TIPODOCUMENTO
   AND PS.SERIEDOCUMENTO=LS.SERIEDOCUMENTO
   AND PS.PREVISAOSAIDA=LS.PREVISAOSAIDA
   AND LS.CODIGOMATRIZ=UC.CODIGOEMPRESA
   AND LS.CODIGOPRODUTO=UC.CODIGOPRODUTO
   AND TRA.CODIGOEMPRESA(+)=PS.CODIGOTRANSPORTADORA
   AND PS.CODIGOESTABELECIMENTO=1
   AND PS.ESTADODOCUMENTO=11
   AND PS.CODIGODEPOSITANTE='53162095002400'
   AND PS.TIPODOCUMENTO IN ('PED','NF')
GROUP BY PS.CODIGOESTABELECIMENTO,
         PS.CODIGOEMPRESA,
         PS.CODIGOTRANSPORTADORA,
         TRA.DESCRICAOEMPRESA,
         PS.DATAEMISSAO,
         PS.DATAGERACAO,
         PS.TIPODOCUMENTO,
         PS.PREVISAOSAIDA,
         LS.CLASSEPRODUTO,
         LS.NUMEROPEDIDOSEPARACAO,
         PS.ESTADODOCUMENTO  