SELECT DS.CODIGODOCUMENTO,
       DS.CODIGOESTABELECIMENTO,
       (SELECT EST.NOMEESTABELECIMENTO FROM ESTABELECIMENTO EST WHERE EST.CODIGOESTABELECIMENTO = DS.CODIGOESTABELECIMENTO) AS NOME_ESTABELECIMENTO,
       DS.CODIGOTRANSPORTADORA,       
       (SELECT E.DESCRICAOEMPRESA FROM EMPRESA E WHERE E.CODIGOEMPRESA = DS.CODIGOTRANSPORTADORA) AS TRANSPORTADORA_NF,
       DS.CODIGOEMPRESA,
       (SELECT E.DESCRICAOEMPRESA FROM EMPRESA E WHERE E.CODIGOEMPRESA = DS.CODIGOEMPRESA) AS DESTINATARIO,
       (SELECT E.CEPEMPRESA FROM EMPRESA E WHERE E.CODIGOEMPRESA = DS.CODIGOEMPRESA) AS CEP,
       (SELECT E.UFEMPRESA FROM EMPRESA E WHERE E.CODIGOEMPRESA = DS.CODIGOEMPRESA) AS UF,
       (SELECT REG.IDREGIAO
          FROM REGIAO REG,
               REGIAOSEQUENCIA REGS
         WHERE REG.CODIGOREGIAO = REGS.CODIGOREGIAO
           AND REPLACE(REGS.CEPINICIAL,'-','') <= (SELECT REPLACE(EMP.CEPEMPRESA,'-','')
                                                    FROM EMPRESA EMP
                                                   WHERE EMP.CODIGOEMPRESA = DS.CODIGOEMPRESA)
           AND REPLACE(REGS.CEPFINAL,'-','') >= (SELECT REPLACE(EMP.CEPEMPRESA,'-','')
                                                  FROM EMPRESA EMP
                                                 WHERE EMP.CODIGOEMPRESA = DS.CODIGOEMPRESA)) AS ROTA,
       (SELECT R.CODIGOROMANEIO 
          FROM ROMANEIO R,
               ROMANEIODOCUMENTO RD
         WHERE R.CODIGOESTABELECIMENTO = DS.CODIGOESTABELECIMENTO
           AND R.CODIGODEPOSITANTE = DS.CODIGODEPOSITANTE
           AND R.CODIGOROMANEIO = RD.CODIGOROMANEIO
           AND RD.NUMERODOCUMENTO = NVL(DS.DOCUMENTOSAIDA,0)) AS NR_ROMANEIO,
       (SELECT DSR.DATAEMISSAO FROM DOCUMENTOSAIDA DSR WHERE DSR.CODIGODEPOSITANTE=DS.CODIGODEPOSITANTE AND DSR.DOCUMENTOSAIDA = LS.NUMEROPEDIDOSEPARACAO) AS DT_EMISSAO_REMESSA,
       (SELECT PS.DATAGERACAO FROM PREVISAOSAIDA PS WHERE PS.CODIGODEPOSITANTE=DS.CODIGODEPOSITANTE AND PS.PREVISAOSAIDA = LS.NUMEROPEDIDOSEPARACAO) AS DT_REMESSA_PREVISAO,
       (SELECT DSR.DATAGERACAO FROM DOCUMENTOSAIDA DSR WHERE DSR.CODIGODEPOSITANTE=DS.CODIGODEPOSITANTE AND DSR.DOCUMENTOSAIDA = LS.NUMEROPEDIDOSEPARACAO) AS DT_REMESSA_VIROU_DS,
       LS.NUMEROPEDIDOSEPARACAO NUMEROREMESSA,
       DECODE(DS.TIPODOCUMENTO,
              'PED',NULL,
       (SELECT DSR.DATAEMISSAO FROM DOCUMENTOSAIDA DSR WHERE DSR.DOCUMENTOSAIDA = DS.DOCUMENTOSAIDA)) AS DT_EMISSAO_NF,
       DECODE(DS.TIPODOCUMENTO,
              'PED',NULL,
       (SELECT DSR.DATAGERACAO FROM DOCUMENTOSAIDA DSR WHERE DSR.DOCUMENTOSAIDA = DS.DOCUMENTOSAIDA)) AS DT_NF_DS,
       DECODE(DS.TIPODOCUMENTO,
              'PED',NULL,
       DS.SERIEDOCUMENTO) AS SERIE_NF,
       DECODE(DS.TIPODOCUMENTO,
              'PED',NULL,
              DS.DOCUMENTOSAIDA) NUMERONF,
       DECODE(DS.TIPODOCUMENTO,
              'NF',DS.QUANTIDADEVOLUME,
       SUM(TRUNC(LS.QTDE/UC.MAXFT))) QTDECX,
       DECODE(SUM(MOD(LS.QTDE,UC.MAXFT)),
              0, 0,
              1) QTDE_CX_FRAC,
       DS.ESTADODOCUMENTO,
       (SELECT EDOC.DESCRICAOESTADODOCUMENTO FROM ESTADODOCUMENTO EDOC WHERE EDOC.ESTADODOCUMENTO = DS.ESTADODOCUMENTO) AS STATUS_DOC      
  FROM DOCUMENTOSAIDA DS,
       (SELECT XLS.CODIGOESTABELECIMENTO,
               XLS.CODIGOMATRIZ,
               XLS.CODIGOEMPRESA,
               XLS.TIPODOCUMENTO,
               XLS.SERIEDOCUMENTO,
               XLS.DOCUMENTOSAIDA,
               XLS.NUMEROPEDIDOSEPARACAO,
               XLS.CODIGOPRODUTO,
               SUM(XLS.QUANTIDADEDOCUMENTO*XLS.FATORTIPOUC) QTDE
          FROM LOTESAIDA XLS
         GROUP BY XLS.CODIGOESTABELECIMENTO,
               XLS.CODIGOMATRIZ,
               XLS.CODIGOEMPRESA,
               XLS.TIPODOCUMENTO,
               XLS.SERIEDOCUMENTO,
               XLS.DOCUMENTOSAIDA,
               XLS.NUMEROPEDIDOSEPARACAO,
               XLS.CODIGOPRODUTO) LS,         
       (SELECT T.CODIGOEMPRESA, T.CODIGOPRODUTO,
               MAX(T.FATORTIPOUC) MAXFT
          FROM TIPOUC T
         WHERE T.FATORTIPOUC > 1
         GROUP BY T.CODIGOEMPRESA, T.CODIGOPRODUTO) UC       
 WHERE DS.CODIGOESTABELECIMENTO=LS.CODIGOESTABELECIMENTO
   AND DS.CODIGOEMPRESA=LS.CODIGOEMPRESA
   AND DS.TIPODOCUMENTO=LS.TIPODOCUMENTO
   AND DS.SERIEDOCUMENTO=LS.SERIEDOCUMENTO
   AND DS.DOCUMENTOSAIDA=LS.DOCUMENTOSAIDA
   AND LS.CODIGOMATRIZ=UC.CODIGOEMPRESA
   AND LS.CODIGOPRODUTO=UC.CODIGOPRODUTO
   AND DS.CODIGOESTABELECIMENTO=1
   AND DS.ESTADODOCUMENTO<>29
   AND DS.CODIGODEPOSITANTE='53162095002400'
   AND DS.TIPODOCUMENTO IN ('PED','NF')  
GROUP BY DS.CODIGODOCUMENTO,
         DS.CODIGOESTABELECIMENTO,
         DS.CODIGOTRANSPORTADORA,
         DS.CODIGOEMPRESA,
         DS.CODIGODEPOSITANTE,
         DS.CODIGODOCUMENTO,
         DS.TIPODOCUMENTO,
         DS.DOCUMENTOSAIDA,
         DS.QUANTIDADEVOLUME,
         LS.NUMEROPEDIDOSEPARACAO,
         DS.SERIEDOCUMENTO,
         DS.ESTADODOCUMENTO     
