SELECT CASE 
          WHEN E2.RUA <= '14' THEN 'FARMACEUTICO'
       ELSE 'OUTROS PRODUTOS'
       END AS AREA,
       E2.RUA,
      (E2.END_LIVRE + E2.END_OCUPADO) AS TOTAL_END,
       E2.END_LIVRE,
       E2.END_OCUPADO,
       E2.END_PICKING
  FROM (SELECT DISTINCT E.RUA AS RUA, 
                (SELECT COUNT(1)
                   FROM VR3_ENDERECODISPONIVEL ED
                  WHERE ED.CODIGOESTABELECIMENTO = E.CODIGOESTABELECIMENTO
                    AND ED.RUA = E.RUA
                    AND ED.TIPOENDERECO = E.TIPOENDERECO
                    AND ED.QTDEESTOQUE <= 0) AS END_LIVRE,
                 (SELECT COUNT(1)
                    FROM VR3_ENDERECODISPONIVEL ED
                   WHERE ED.CODIGOESTABELECIMENTO = E.CODIGOESTABELECIMENTO
                     AND ED.RUA = E.RUA
                     AND ED.TIPOENDERECO = E.TIPOENDERECO
                     AND ED.QTDEESTOQUE > 0) AS END_OCUPADO,
                 (SELECT COUNT(1)
                    FROM PRODUTOPICKING PPK
                   WHERE PPK.CODIGOESTABELECIMENTO = E.CODIGOESTABELECIMENTO
                     AND (SELECT E1.RUA FROM ENDERECO E1 WHERE E1.ENDERECO = PPK.ENDERECOPADRAO) = E.RUA) AS END_PICKING         
          FROM ENDERECO E
         WHERE E.CODIGOESTABELECIMENTO = 1
           AND E.PREDIO = 'A'
           AND E.TIPOENDERECO = 170
           AND E.DISPONIVEL = 1      
)E2

UNION

SELECT 'TOTAL' AS AREA,
    TO_CHAR(COUNT(E3.RUA)),
      SUM((E3.END_LIVRE + E3.END_OCUPADO)) AS TOTAL_END,
      SUM(E3.END_LIVRE),
      SUM(E3.END_OCUPADO),
      SUM(E3.END_PICKING)
  FROM (SELECT DISTINCT E.RUA AS RUA, 
                (SELECT COUNT(1)
                   FROM VR3_ENDERECODISPONIVEL ED
                  WHERE ED.CODIGOESTABELECIMENTO = E.CODIGOESTABELECIMENTO
                    AND ED.RUA = E.RUA
                    AND ED.TIPOENDERECO = E.TIPOENDERECO
                    AND ED.QTDEESTOQUE <= 0) AS END_LIVRE,
                 (SELECT COUNT(1)
                    FROM VR3_ENDERECODISPONIVEL ED
                   WHERE ED.CODIGOESTABELECIMENTO = E.CODIGOESTABELECIMENTO
                     AND ED.RUA = E.RUA
                     AND ED.TIPOENDERECO = E.TIPOENDERECO
                     AND ED.QTDEESTOQUE > 0) AS END_OCUPADO,
                 (SELECT COUNT(1)
                    FROM PRODUTOPICKING PPK
                   WHERE PPK.CODIGOESTABELECIMENTO = E.CODIGOESTABELECIMENTO
                     AND (SELECT E1.RUA FROM ENDERECO E1 WHERE E1.ENDERECO = PPK.ENDERECOPADRAO) = E.RUA) AS END_PICKING         
          FROM ENDERECO E
         WHERE E.CODIGOESTABELECIMENTO = 1
           AND E.PREDIO = 'A'
           AND E.TIPOENDERECO = 170
           AND E.DISPONIVEL = 1      
)E3
ORDER BY AREA
         --E2.RUA
