-- Para Bloquear os Usuários: UPDATE SEGUSUARIO SU SET SU.USUARIOBLOQUEADO = 1
-- Para Alterar a senha dos Usuários: UPDATE SEGUSUARIOSENHA SS SET SS.SENHA = 'XXX'

SELECT *
  FROM SEGUSUARIO SU
 WHERE SU.USUARIOBLOQUEADO = 0
   AND SU.ACESSOADMINISTRADOR = 0

-- Para Bloquear os Usuários:
UPDATE SEGUSUARIO SU SET SU.USUARIOBLOQUEADO = 1, SU.DATABLOQUEIO = SYSDATE
WHERE SU.USUARIOBLOQUEADO = 0
  AND SU.ACESSOADMINISTRADOR = 0

SELECT *
  FROM SEGUSUARIOSENHA SS
 WHERE SS.ATIVO = 1

-- Para Alterar a senha dos Usuários:
-- A senha sera alterada para gat5135    
UPDATE SEGUSUARIOSENHA SS SET SS.SENHA = '5612205A635646', SS.DATASENHA = SYSDATE
WHERE SS.ATIVO = 1                        
