--CREATOR: KELSEN LIMA
-- QR MOVIMENTACAO DE PRODUTO EXPEDICAO

CREATE OR REPLACE VIEW VR_MOVEXPEDICAOPRODUTO_PESOOFI AS
SELECT DS.CODIGOESTABELECIMENTO,
       (SELECT EST.NOMEESTABELECIMENTO
          FROM ESTABELECIMENTO EST
         WHERE EST.CODIGOESTABELECIMENTO = DS.CODIGOESTABELECIMENTO) AS NOMEESTABELECIMENTO,
       DS.CODIGODEPOSITANTE,
       (SELECT DEP.DESCRICAOEMPRESA
          FROM EMPRESA DEP
         WHERE DEP.CODIGOEMPRESA = DS.CODIGODEPOSITANTE) AS DESCRICAODEPOSITANTE,
       DS.DATAMOVIMENTO,
       LS.CODIGOPRODUTO,
       PRO.DESCRICAOPRODUTO,
       PRO.CODIGOGRUPO,
       PRO.CODIGOSUBGRUPO,
       PRO.CODIGOCATEGORIA,
       PRO.CODIGOPUBLICOALVO,
       DS.CODIGOEMPRESA,
       DS.TIPODOCUMENTO,
       DS.SERIEDOCUMENTO,
       DS.DOCUMENTOSAIDA,
       (SELECT DISTINCT DOSIL.DOCUMENTOOFICIALSAIDA
          FROM DOCUMENTOOFICIALSAIDAITEMLOTE DOSIL
         WHERE DOSIL.CODIGOESTABELECIMENTO = DS.CODIGOESTABELECIMENTO
           AND DOSIL.LOTESAIDA = LS.LOTESAIDA
           AND ROWNUM = 1) AS DOCUMENTOOFICIALSAIDA,
       LS.LOTESAIDA,
       LS.NUMEROREVISAO,
       LS.CLASSEPRODUTO,
       LES.TIPOUC,
       LES.FATORTIPOUC,
       SUM(LSS.QUANTIDADESAIDA) AS QUANTIDADESAIDA,
       SUM(LSS.QUANTIDADESAIDA / LES.FATORTIPOUC) AS QUANTIDADESAIDAF,
       LES.PESOBRUTO AS PESOBRUTO,
       SUM(LSS.QUANTIDADESAIDA / LES.FATORTIPOUC) * LES.PESOBRUTO AS PESOBRUTOT,
       (SELECT SUM(DOSIL.QUANTIDADEATENDIDA)
          FROM DOCUMENTOOFICIALSAIDAITEMLOTE DOSIL
         WHERE DOSIL.CODIGOESTABELECIMENTO = DS.CODIGOESTABELECIMENTO
           AND DOSIL.LOTESAIDA = LS.LOTESAIDA)  AS QUANTIDADEATENDIDA
  FROM DOCUMENTOSAIDA DS,
       LOTESAIDA LS,
       PRODUTO PRO,
       LOTESAIDASEQUENCIA LSS,
       LOTEENTRADASEQUENCIA LES
 WHERE DS.CODIGOESTABELECIMENTO = LS.CODIGOESTABELECIMENTO
   AND DS.CODIGOEMPRESA = LS.CODIGOEMPRESA
   AND DS.TIPODOCUMENTO = LS.TIPODOCUMENTO
   AND DS.SERIEDOCUMENTO = LS.SERIEDOCUMENTO
   AND DS.DOCUMENTOSAIDA = LS.DOCUMENTOSAIDA
   AND LS.CODIGOMATRIZ = PRO.CODIGOEMPRESA
   AND LS.CODIGOPRODUTO = PRO.CODIGOPRODUTO
   AND LS.CODIGOESTABELECIMENTO = LSS.CODIGOESTABELECIMENTO
   AND LS.LOTESAIDA = LSS.LOTESAIDA
   AND LSS.CODIGOESTABELECIMENTO = LES.CODIGOESTABELECIMENTO
   AND LSS.LOTEENTRADA = LES.LOTEENTRADA
   AND LSS.LOTEENTRADASEQUENCIA = LES.LOTEENTRADASEQUENCIA
 GROUP BY DS.CODIGOESTABELECIMENTO,
       DS.CODIGODEPOSITANTE,
       DS.DATAMOVIMENTO,
       LS.CODIGOPRODUTO,
       PRO.DESCRICAOPRODUTO,
       PRO.CODIGOGRUPO,
       PRO.CODIGOSUBGRUPO,
       PRO.CODIGOCATEGORIA,
       PRO.CODIGOPUBLICOALVO,
       DS.CODIGOEMPRESA,
       DS.TIPODOCUMENTO,
       DS.SERIEDOCUMENTO,
       DS.DOCUMENTOSAIDA,
       LS.LOTESAIDA,
       LS.NUMEROREVISAO,
       LS.CLASSEPRODUTO,
       LES.TIPOUC,
       LES.FATORTIPOUC,
       LES.PESOBRUTO
 ORDER BY DS.CODIGOESTABELECIMENTO,
       DS.CODIGODEPOSITANTE,
       DS.DATAMOVIMENTO,
       LS.CODIGOPRODUTO ASC
/